name: Android Emulator Windows
on:
  # Manual Run.
  workflow_dispatch:  
  
  # On a push to a branch or tag.
  push:
    branches: [ master ]

  # On a PR to a branch or tag.
  pull_request:
    branches: [ master ]
    
  # On a release.
  release:
    types:
      - published

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Emulator
      run: powershell -executionpolicy bypass "& '${env:ANDROID_HOME}\tools\bin\sdkmanager' --install emulator"

    - name: Accel Check
      shell: cmd
      run: powershell -executionpolicy bypass "& '${env:ANDROID_HOME}\emulator\emulator' -accel-check"