name: Build
on:
  # Manual Run.
  workflow_dispatch:  
  
  # On a push to a branch or tag.
  push:
    branches: [ master ]

  # On a PR to a branch or tag.
  pull_request:
    branches: [ master ]
    
  # On a release.
  release:
    types:
      - published

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: HAXM Check
      run: sc query intelhaxm
